# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-25 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20181125_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image2',
            new_name='image_two',
        ),
    ]
